-- Auto-generated seed data from lib/data.ts
-- Run this in Supabase SQL Editor AFTER running schema.sql

insert into listings (
  id, title, plot_type, city, locality, state, area_sqft, price_lakh,
  price_per_sqft, facing, road_width_ft, dimensions, zone, features,
  description, verified, status, seller_name, seller_type, seller_phone,
  lat, lng, images
) values
(
  'kp-lonavla-001',
  'Hillside NA Plot near Lonavla Lake',
  'Residential',
  'Lonavla',
  'Tungarli',
  'Maharashtra',
  4500,
  67.5,
  1500,
  'East',
  24,
  '75 x 60 ft',
  'NA Residential',
  '{"Gated community","Lake view","Water connection","Electricity on site"}',
  'A north-east facing NA plot tucked in the hills of Tungarli, a 10-minute drive from Lonavla Lake. The plot sits in an approved layout with wide internal roads and is ready for construction with all conversion paperwork in place.',
  true,
  'live',
  'Suresh Patil',
  'Owner',
  '+91 98XXX XX234',
  18.7546,
  73.4062,
  6
),
(
  'kp-lonavla-002',
  'Open Farmland with Mango Orchard',
  'Agricultural',
  'Lonavla',
  'Kune Village',
  'Maharashtra',
  87120,
  95,
  109,
  'North',
  12,
  '2 Acres',
  'Agricultural',
  '{"30+ mango trees","Borewell","Mud road access","Hill backdrop"}',
  'Two acres of fertile agricultural land near Kune village, planted with mature mango and chikoo trees. A seasonal stream runs along the northern boundary. Ideal for a weekend farm or organic farming venture.',
  true,
  'live',
  'Vitthal Shinde',
  'Owner',
  '+91 97XXX XX812',
  18.7281,
  73.391,
  5
),
(
  'kp-pune-001',
  'Corner Plot on Highway, Near IT Park',
  'Commercial',
  'Pune',
  'Hinjawadi Phase 3',
  'Maharashtra',
  6000,
  480,
  8000,
  'North-East',
  40,
  '100 x 60 ft',
  'Commercial',
  '{"Highway facing","High footfall","Near metro line","Commercial NA"}',
  'Premium corner commercial plot on the main Hinjawadi–Wakad road, 800m from the upcoming metro station. Suitable for showroom, office complex or retail development. Heavy daily footfall from IT crowd.',
  true,
  'live',
  'Kunal Deshmukh',
  'Agent',
  '+91 98XXX XX120',
  18.5908,
  73.7392,
  8
),
(
  'kp-pune-002',
  'Ready-to-Build Plot in Gated Layout',
  'Residential',
  'Pune',
  'Bavdhan',
  'Maharashtra',
  2400,
  144,
  6000,
  'South',
  30,
  '40 x 60 ft',
  'Residential NA',
  '{"Gated layout","Underground drainage","Streetlights","Clubhouse"}',
  'Well-planned plot inside a 40-acre gated township in Bavdhan with underground utilities, paver roads and a clubhouse already operational. Close to schools and the Mumbai-Bangalore highway.',
  true,
  'live',
  'Anjali Construction',
  'Builder',
  '+91 99XXX XX556',
  18.5089,
  73.7768,
  7
),
(
  'kp-pune-003',
  'Investment Plot near Ring Road',
  'Residential',
  'Pune',
  'Urse',
  'Maharashtra',
  3000,
  54,
  1800,
  'West',
  20,
  '50 x 60 ft',
  'Residential NA',
  '{"Near ring road","Appreciating zone","Clear title","7/12 verified"}',
  'Affordable NA plot in Urse, directly impacted by the upcoming Pune Ring Road alignment. Clear and marketable title with all documents verified. Good for long-term appreciation.',
  true,
  'live',
  'Ramesh Jadhav',
  'Owner',
  '+91 96XXX XX330',
  18.7235,
  73.5829,
  4
),
(
  'kp-nashik-001',
  'Vineyard-Ready Agricultural Land',
  'Agricultural',
  'Nashik',
  'Dindori Road',
  'Maharashtra',
  130680,
  78,
  60,
  'East',
  18,
  '3 Acres',
  'Agricultural',
  '{"Drip irrigation ready","Borewell + bore pump","Near wineries","Fertile red soil"}',
  'Three acres of red soil farmland on Dindori Road, the heart of Nashik''s wine country. Currently used for grape cultivation with drip irrigation infrastructure already laid. Excellent soil and water table.',
  true,
  'live',
  'Bharat Pawar',
  'Owner',
  '+91 95XXX XX441',
  20.0382,
  73.7466,
  6
),
(
  'kp-nashik-002',
  'Riverside Farmhouse Plot',
  'Farmhouse',
  'Nashik',
  'Igatpuri',
  'Maharashtra',
  21780,
  42,
  193,
  'North',
  15,
  '0.5 Acre',
  'NA Farmhouse',
  '{"River frontage","Hill view","Approach road","Fruit trees"}',
  'Half-acre plot bordering a seasonal river in Igatpuri with views of the Western Ghats. Already has a few jackfruit and coconut trees. Suitable for a weekend farmhouse retreat near Mumbai-Nashik highway.',
  false,
  'live',
  'Meena Travels & Properties',
  'Agent',
  '+91 94XXX XX772',
  19.6964,
  73.5626,
  5
),
(
  'kp-lonavla-003',
  'Compact Residential Plot in Town',
  'Residential',
  'Lonavla',
  'Shivaji Nagar',
  'Maharashtra',
  1800,
  45,
  2500,
  'East',
  18,
  '36 x 50 ft',
  'Residential',
  '{"Walking distance to station","Municipal water","Existing boundary wall"}',
  'Compact plot in the heart of Lonavla town, walking distance to the railway station and main market. Boundary wall already constructed. Ideal for a small home or guesthouse given the tourist footfall.',
  true,
  'live',
  'Pooja Realtors',
  'Agent',
  '+91 93XXX XX905',
  18.7506,
  73.4071,
  4
),
(
  'kp-mumbai-001',
  'Sea-Facing Plot in Upcoming Township',
  'Residential',
  'Mumbai',
  'Panvel',
  'Maharashtra',
  3200,
  320,
  10000,
  'West',
  36,
  '40 x 80 ft',
  'Residential NA',
  '{"Sea-facing","Near upcoming airport","Gated township","Clear title"}',
  'Premium NA plot in a master-planned township near Navi Mumbai International Airport, with partial sea views. Roads, drainage and electricity already laid out across the layout.',
  true,
  'live',
  'Coastal Estates',
  'Builder',
  '+91 98XXX XX671',
  18.9894,
  73.1175,
  9
),
(
  'kp-pune-004',
  'Warehouse Plot near Logistics Park',
  'Industrial',
  'Pune',
  'Chakan',
  'Maharashtra',
  21780,
  110,
  505,
  'East',
  60,
  '0.5 Acre',
  'Industrial',
  '{"Highway access","Near auto manufacturing hub","Power connection ready","MIDC approved"}',
  'MIDC-approved industrial plot in Chakan, close to major auto manufacturing plants and the Pune-Nashik highway. Suitable for warehousing, logistics or light manufacturing.',
  true,
  'live',
  'Chakan Industrial Estate',
  'Agent',
  '+91 99XXX XX204',
  18.7553,
  73.8612,
  5
),
(
  'kp-delhi-001',
  'Farmhouse Plot on Gurgaon-Sohna Road',
  'Farmhouse',
  'Gurgaon',
  'Sohna Road',
  'Haryana',
  87120,
  850,
  976,
  'North',
  40,
  '2 Acres',
  'NA Farmhouse',
  '{"Aravalli hill view","Gated farmhouse colony","Borewell","24x7 security"}',
  'Two-acre farmhouse plot in a premium gated colony off Sohna Road, with Aravalli hill views and existing greenery. Popular weekend-home belt for Delhi-NCR buyers.',
  true,
  'live',
  'NCR Land Co.',
  'Agent',
  '+91 97XXX XX318',
  28.3789,
  77.0497,
  7
),
(
  'kp-delhi-002',
  'Commercial Plot near Dwarka Expressway',
  'Commercial',
  'Gurgaon',
  'Sector 99',
  'Haryana',
  4500,
  675,
  15000,
  'South',
  50,
  '75 x 60 ft',
  'Commercial',
  '{"Dwarka Expressway frontage","High visibility","Mixed-use zoning","Metro connectivity planned"}',
  'Commercial plot with direct frontage on Dwarka Expressway, in a rapidly developing sector with several residential towers nearby. Suitable for retail, office or mixed-use development.',
  true,
  'live',
  'Capital Realty Partners',
  'Agent',
  '+91 96XXX XX902',
  28.4732,
  76.9794,
  6
),
(
  'kp-bengaluru-001',
  'BMRDA-Approved Plot near Tech Corridor',
  'Residential',
  'Bengaluru',
  'Sarjapur Road',
  'Karnataka',
  2400,
  168,
  7000,
  'East',
  30,
  '30 x 80 ft',
  'Residential BMRDA',
  '{"BMRDA approved","Near IT corridor","Clubhouse layout","Underground utilities"}',
  'BMRDA-approved plot in a gated layout on Sarjapur Road, close to major tech parks. Layout includes underground drainage, paver roads and a clubhouse under construction.',
  true,
  'live',
  'Sarjapur Greens Pvt Ltd',
  'Builder',
  '+91 95XXX XX663',
  12.9081,
  77.6873,
  8
),
(
  'kp-bengaluru-002',
  'Agricultural Land near Nandi Hills',
  'Agricultural',
  'Bengaluru',
  'Devanahalli',
  'Karnataka',
  65340,
  90,
  138,
  'North-East',
  16,
  '1.5 Acres',
  'Agricultural',
  '{"Near Nandi Hills","Borewell","Coconut plantation","Near airport"}',
  '1.5 acres of agricultural land near Devanahalli, within easy reach of Kempegowda International Airport and Nandi Hills. Currently has a mature coconut plantation and functioning borewell.',
  false,
  'live',
  'Lakshmi Devaraj',
  'Owner',
  '+91 94XXX XX519',
  13.2437,
  77.6907,
  4
),
(
  'kp-jaipur-001',
  'Heritage-Zone Residential Plot',
  'Residential',
  'Jaipur',
  'Vaishali Nagar',
  'Rajasthan',
  1800,
  54,
  3000,
  'East',
  24,
  '30 x 60 ft',
  'Residential',
  '{"JDA approved","Near shopping malls","Water & sewer connected","Wide road"}',
  'JDA-approved residential plot in the established Vaishali Nagar locality, close to malls, schools and hospitals. All utility connections already in place.',
  true,
  'live',
  'Rajendra Sharma',
  'Owner',
  '+91 93XXX XX247',
  26.9115,
  75.7392,
  5
),
(
  'kp-jaipur-002',
  'Farmland with Aravalli Views',
  'Agricultural',
  'Jaipur',
  'Chaksu',
  'Rajasthan',
  217800,
  60,
  28,
  'South',
  14,
  '5 Acres',
  'Agricultural',
  '{"Aravalli range views","Tubewell","Mustard fields","Mud road access"}',
  'Five acres of farmland near Chaksu with views of the Aravalli range, currently cultivated with mustard and bajra. Tubewell installed and functioning. Good for large-scale farming or future land banking.',
  true,
  'live',
  'Mohan Lal Yadav',
  'Owner',
  '+91 92XXX XX835',
  26.5993,
  75.9508,
  3
),
(
  'kp-navimumbai-001',
  'Plot near Navi Mumbai International Airport',
  'Residential',
  'Navi Mumbai',
  'Ulwe',
  'Maharashtra',
  2700,
  270,
  10000,
  'East',
  30,
  '45 x 60 ft',
  'Residential NA',
  '{"Near new airport","CIDCO layout","Metro line planned","High appreciation zone"}',
  'NA plot in Ulwe, within a CIDCO-developed layout and just a few kilometers from the upcoming Navi Mumbai International Airport. One of the most actively traded land markets in the region given the airport-led growth.',
  true,
  'live',
  'CIDCO Land Brokers',
  'Agent',
  '+91 98XXX XX014',
  18.9894,
  73.0179,
  6
),
(
  'kp-navimumbai-002',
  'Commercial Plot on Sion-Panvel Highway',
  'Commercial',
  'Navi Mumbai',
  'Kharghar',
  'Maharashtra',
  5400,
  810,
  15000,
  'West',
  45,
  '90 x 60 ft',
  'Commercial',
  '{"Highway frontage","Near Kharghar Central Park","High footfall","Metro connectivity"}',
  'Commercial plot with direct frontage on the Sion-Panvel Highway in Kharghar, close to the central business district and metro station. Suited for retail, hospitality or office development.',
  true,
  'live',
  'Kharghar Estates',
  'Builder',
  '+91 97XXX XX566',
  19.0474,
  73.0699,
  7
),
(
  'kp-dholera-001',
  'SIR-Approved Residential Plot in Dholera SIR',
  'Residential',
  'Dholera',
  'Dholera SIR, Sector 9',
  'Gujarat',
  1800,
  18,
  1000,
  'North',
  18,
  '30 x 60 ft',
  'Residential SIR',
  '{"Inside Dholera SIR boundary","Near upcoming airport","Govt-approved layout","Title clear"}',
  'Residential plot within India''s first greenfield Special Investment Region (SIR), near the planned Dholera International Airport and the Delhi-Mumbai Industrial Corridor. Early-stage entry point in a government-backed smart city development.',
  true,
  'live',
  'Dholera Land Ventures',
  'Agent',
  '+91 99XXX XX381',
  22.2493,
  72.1909,
  4
),
(
  'kp-dholera-002',
  'Industrial Land near Dholera Activation Area',
  'Industrial',
  'Dholera',
  'Dholera SIR, Sector 14',
  'Gujarat',
  217800,
  125,
  57,
  'South',
  30,
  '5 Acres',
  'Industrial SIR',
  '{"DMIC corridor","Near activation area","Flat terrain","Govt infrastructure planned"}',
  'Five acres of industrial-zoned land in Dholera SIR''s activation area, part of the Delhi-Mumbai Industrial Corridor. Flat, well-connected terrain earmarked for manufacturing and logistics development as the smart city rolls out.',
  true,
  'live',
  'Gujarat Industrial Plots Co.',
  'Agent',
  '+91 96XXX XX709',
  22.2367,
  72.1654,
  5
),
(
  'kp-goa-001',
  'Beach-Adjacent Plot in North Goa',
  'Residential',
  'Goa',
  'Assagao',
  'Goa',
  4000,
  320,
  8000,
  'West',
  20,
  '0.09 Acres x 1',
  'Residential Settlement Zone',
  '{"10-min from Anjuna beach","Coconut grove","Settlement zone","Popular with NRI buyers"}',
  'Plot in a quiet pocket of Assagao, North Goa''s most sought-after village for boutique villas and cafes. Settlement-zone land surrounded by coconut groves, a short drive from Anjuna and Vagator beaches. Strong demand from NRI and lifestyle buyers.',
  true,
  'live',
  'Goa Coastal Properties',
  'Agent',
  '+91 95XXX XX247',
  15.5937,
  73.7726,
  8
),
(
  'kp-goa-002',
  'Riverfront Farmland in South Goa',
  'Agricultural',
  'Goa',
  'Cortalim',
  'Goa',
  43560,
  85,
  195,
  'East',
  14,
  '1 Acre',
  'Agricultural / Orchard',
  '{"Zuari river frontage","Cashew & mango trees","Quiet village setting","30 min from Panaji"}',
  'One acre of riverfront farmland in Cortalim along the Zuari river, planted with cashew and mango trees. A peaceful South Goa setting roughly 30 minutes from Panaji — well suited for a farm retreat or long-term land holding.',
  false,
  'live',
  'Maria Fernandes',
  'Owner',
  '+91 94XXX XX602',
  15.3953,
  73.9143,
  5
)
on conflict (id) do nothing;
